services:
  database:
    image: postgres:latest
    container_name: nest_postgres_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    networks:
      - prisma-network
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "psql -U ${DB_USER} -d ${DB_NAME} -c 'SELECT 1' || exit 1",
        ]
      interval: 10s
      timeout: 2s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: '10m'
        max-file: '3'

  redis:
    image: redis:latest
    container_name: nest_redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - prisma-network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 2s
      retries: 5
    logging:
      options:
        max-size: '10m'
        max-file: '3'

networks:
  prisma-network:

volumes:
  postgres_data:
  redis_data:
