services:
  database:
    image: postgres:latest
    container_name: nest_postgres_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    networks:
      - prisma-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 2s
      retries: 20
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: '10m'
        max-file: '3'

networks:
  prisma-network:

volumes:
  postgres_data:
